import { site } from '$lib/content';
import type { PrivacyContent } from '$lib/privacyContent';

export const ungeulPrivacyContent: Record<'ko' | 'en', PrivacyContent> = {
	ko: {
		title: '운글 개인정보 처리방침',
		description:
			'운글의 기기 내 사주 입력 정보, 가명 인증 및 풀이 콘텐츠 처리에 관한 개인정보 처리방침입니다.',
		kicker: 'Ungeul Privacy Policy',
		lastUpdated: '2026년 8월 21일',
		lastUpdatedLabel: '시행일 및 최종 수정일',
		backLabel: '서리랩스 홈으로',
		languageLabel: '언어',
		intro:
			'이 방침은 Seori Labs가 제공하는 「운글: 사주 몰라도 읽히는 풀이」(Android 패키지 및 iOS 번들 ID com.seorilabs.ungeul, 이하 “앱”)에 적용됩니다. 앱의 실제 데이터 처리와 스토어 표시가 공통 방침과 다른 경우 이 제품별 방침이 우선합니다.',
		sections: [
			{
				title: '앱이 처리하는 데이터',
				body: [
					'이용자가 입력한 프로필명, 원본 생년월일, 태어난 시각과 출생 장소는 이용자의 기기에만 저장됩니다. Seori Labs 서버나 Firebase에 원본 입력값을 저장하지 않으며, 앱을 삭제하거나 앱 안에서 프로필을 삭제하면 기기 저장 정보가 제거됩니다.',
					'앱은 이름이나 이메일을 요구하지 않습니다. 앱 기능 제공을 위해 Firebase와 Seori Labs Platform이 생성한 가명 사용자 식별자, 인증 토큰과 세션 정보를 처리합니다.',
					'읽기 쉬운 풀이 콘텐츠를 제공하기 위해 기기에서 계산한 명식의 파생 사실(예: 오행·십성·대운·세운·월운에 필요한 분류값)과 콘텐츠 요청을 Seori Labs Platform으로 전송합니다. 원본 프로필명·생년월일·시각·장소는 전송하지 않습니다.',
					'서비스 보호와 장애 확인을 위해 Firebase App Check의 앱·기기 무결성 신호, 요청 시각·응답 상태·가명 사용자 식별자 등 최소한의 요청 메타데이터와 서버 진단 로그를 처리할 수 있습니다.',
					'첫 내부 테스트 버전 v0.1.0에서는 운영 Google Analytics, 광고와 인앱결제를 사용하지 않습니다. 위치 권한, 연락처, 사진, 동영상, 마이크, 건강 정보와 광고 식별자를 수집하지 않습니다.'
				]
			},
			{
				title: '처리 목적',
				body: [
					'가명 식별자와 인증 정보는 이용자별 콘텐츠 요청을 안전하게 처리하고 무단 사용을 방지하기 위해 사용합니다.',
					'파생 명식 사실과 콘텐츠 요청은 이용자가 선택한 명식·오행·십성·대운·세운·월운 풀이를 제공하기 위해 사용합니다.',
					'App Check 신호와 진단 로그는 자동화된 남용 방지, 서비스 안정성 확인과 오류 대응을 위해 사용합니다.'
				]
			},
			{
				title: '처리 위탁과 국외 처리',
				body: [
					'Seori Labs는 개인정보를 판매하거나 광고 목적으로 공유하지 않습니다.',
					'Google Firebase와 Google Cloud는 인증, App Check, 서버 실행과 로그 처리를 위해 Seori Labs의 서비스 제공자로서 데이터를 처리합니다. Google Play, Apple App Store와 AppsInToss·토스는 각 마켓의 앱 배포와 보안 기능을 처리합니다.',
					'서버로 전송되는 데이터는 HTTPS/TLS로 암호화됩니다. 서비스 제공자의 서버 위치에 따라 데이터가 국외에서 처리될 수 있습니다.'
				]
			},
			{
				title: '보관과 삭제',
				body: [
					'기기 내 프로필과 원본 입력 정보는 이용자가 프로필 또는 앱을 삭제할 때 제거됩니다.',
					'가명 인증 정보, 콘텐츠 요청과 보안·진단 로그는 앱 기능 제공, 장애 대응, 부정 이용 방지와 법적 의무에 필요한 기간 동안 보관한 뒤 삭제하거나 비식별화합니다. 각 클라우드 서비스의 설정된 보관 기간도 적용됩니다.',
					`가명 서버 데이터의 열람 또는 삭제를 요청하려면 ${site.email}로 문의해 주세요. 다른 이용자의 데이터 보호를 위해 앱 설치와 요청에 관한 최소한의 확인을 요청할 수 있습니다.`
				]
			},
			{
				title: '아동과 이용상 주의',
				body: [
					'앱은 아동 전용 서비스로 설계되지 않았으며, 아동임을 알고 개인정보를 수집하지 않습니다.',
					'운글의 풀이는 전통 명리 체계를 이해하기 쉽게 정리한 참고 콘텐츠입니다. 전문적인 의료·법률·투자 판단이나 진단을 대신하지 않습니다.'
				]
			},
			{
				title: '권리와 문의',
				body: [
					'이용자는 적용되는 법령에 따라 자신의 개인정보에 대한 열람, 정정, 삭제, 처리 제한과 이의를 요청할 수 있습니다.',
					'데이터 처리 방식이 변경되면 이 페이지와 Google Play Data safety, Apple App Privacy 및 AppsInToss 등록 정보를 함께 갱신합니다.',
					`개인정보 및 앱 지원 문의: ${site.email}`
				]
			}
		],
		footerNote:
			'이 제품별 방침은 Google Play, Apple App Store와 AppsInToss의 앱 개인정보 표시에 연결됩니다.'
	},
	en: {
		title: 'Ungeul Privacy Policy',
		description:
			'Privacy Policy for on-device birth-profile inputs, pseudonymous authentication, and reading-content processing in Ungeul.',
		kicker: 'Ungeul Privacy Policy',
		lastUpdated: 'August 21, 2026',
		lastUpdatedLabel: 'Effective and last updated',
		backLabel: 'Back to Seori Labs',
		languageLabel: 'Language',
		intro:
			'This policy applies to “Ungeul: Saju Read in Plain Words” (Android package and iOS bundle ID com.seorilabs.ungeul, the “App”), provided by Seori Labs. If the App’s actual processing or store disclosure differs from the general policy, this product-specific policy controls.',
		sections: [
			{
				title: 'Data the App processes',
				body: [
					'Profile names, original dates of birth, birth times, and birth places entered by users are stored only on the user’s device. Seori Labs does not store these original inputs on its servers or in Firebase. They are removed when the user deletes the profile in the App or deletes the App.',
					'The App does not require a name or email address. It processes pseudonymous user identifiers, authentication tokens, and session information generated by Firebase and the Seori Labs Platform to provide App functionality.',
					'To provide plain-language readings, the App sends derived chart facts calculated on the device (such as classifications needed for the five elements, ten gods, decade, annual, and monthly flows) and content requests to the Seori Labs Platform. Original profile names, dates of birth, birth times, and birth places are not sent.',
					'To protect the service and diagnose failures, the App may process Firebase App Check app/device-integrity signals and minimal request metadata and server diagnostic logs, such as request time, response status, and a pseudonymous user identifier.',
					'The first internal-test release, v0.1.0, does not use production Google Analytics, advertising, or in-app purchases. The App does not collect location permission data, contacts, photos, videos, microphone data, health data, or advertising identifiers.'
				]
			},
			{
				title: 'Purposes of processing',
				body: [
					'Pseudonymous identifiers and authentication information are used to process each user’s content requests securely and prevent unauthorized use.',
					'Derived chart facts and content requests are used to provide the chart, five-elements, ten-gods, decade, annual, and monthly readings selected by the user.',
					'App Check signals and diagnostic logs are used to prevent automated abuse, maintain service reliability, and respond to errors.'
				]
			},
			{
				title: 'Service providers and international processing',
				body: [
					'Seori Labs does not sell personal data or share it for advertising.',
					'Google Firebase and Google Cloud process data as service providers for authentication, App Check, server execution, and logging. Google Play, the Apple App Store, and AppsInToss/Toss process distribution and security functions for their respective markets.',
					'Data sent to servers is encrypted with HTTPS/TLS. Data may be processed outside the user’s country depending on service-provider infrastructure.'
				]
			},
			{
				title: 'Retention and deletion',
				body: [
					'On-device profiles and original inputs are removed when the user deletes the profile or the App.',
					'Pseudonymous authentication information, content requests, and security/diagnostic logs are retained only as needed for App functionality, incident response, abuse prevention, and legal obligations, and are then deleted or de-identified. Configured retention periods of the relevant cloud services also apply.',
					`To request access to or deletion of pseudonymous server data, contact ${site.email}. We may request minimal information about the App installation and request to protect other users’ data.`
				]
			},
			{
				title: 'Children and important notice',
				body: [
					'The App is not designed as a child-directed service, and Seori Labs does not knowingly collect personal data from children.',
					'Ungeul provides reference content that explains traditional East Asian fortune-reading concepts. It does not replace professional medical, legal, or investment advice or diagnosis.'
				]
			},
			{
				title: 'Your rights and contact',
				body: [
					'Subject to applicable law, users may request access, correction, deletion, restriction, or objection regarding their personal data.',
					'If data handling changes, we will update this page and the Google Play Data safety, Apple App Privacy, and AppsInToss disclosures together.',
					`Privacy and App support: ${site.email}`
				]
			}
		],
		footerNote:
			'This product-specific policy is linked from the App disclosures on Google Play, the Apple App Store, and AppsInToss.'
	}
};
